name: Notion to Github Sync

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write # Ensures write permissions for GITHUB_TOKEN

jobs:
  fetch-notion-content:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for pull/rebase

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies (root consolidated)
      - name: Install dependencies
        run: npm install

      # Step 4: Fetch Notion Content (with checksum cache)
      - name: Fetch Notion Content
        working-directory: ./project
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: |
          echo "Using API Key: ${NOTION_API_KEY:0:4}***"
          echo "Using Page ID: ${NOTION_PAGE_ID}"
          # Pre-compute old checksum (if any)
          if [ -f ../readme.md ]; then
            sha_old=$(shasum ../readme.md | awk '{print $1}')
          else
            sha_old="NONE"
          fi
          echo "Previous README checksum: $sha_old"
          node notion-sync.js > notion-output.log
          sha_new=$(shasum ../readme.md | awk '{print $1}')
          echo "New README checksum: $sha_new"
          if [ "$sha_old" = "$sha_new" ]; then
            echo "No content change detected; skipping commit." > no_change.flag
          fi

      # Step 5: Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 6: Pull Remote Changes Before Committing
      - name: Pull Remote Changes
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      # Step 7: Track changes only if README changed
      - name: Track Changes (conditional)
        run: |
          if [ -f project/no_change.flag ]; then
            echo "Skipping staging because no_change.flag present.";
            exit 0;
          fi
          git add readme.md
          git status

      # Step 8: Commit and Push (only if changed)
      - name: Commit and Push Changes
        run: |
          if [ -f project/no_change.flag ]; then
            echo "No changes; skipping commit & push."; exit 0; fi
          git commit -m "Update: Fetched new Notion content"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Final Debugging Output
      - name: Confirm Push Success
        run: |
          echo "Latest commit:"
          git log -1
